controllers/ApiController.php
<?php
/**
 * webtoilet
 * User: Nick Sahnovsky
 * Date: 21.10.14
 * Time: 11:33
 */

namespace app\controllers;


use app\components\Toilet;
use yii\web\Controller;

class ApiController extends Controller{

    public function actionStatus(){
        /** @var Toilet $Toilet */
        $Toilet = \Yii::$app->toilet;
        $data = ['status' => $Toilet->getStatus()];
        $data['visits_today'] = $Toilet->getVisitsToday();
        $data['version'] = $Toilet->getVersion();

        \Yii::$app->getResponse()->data = $data;
        \Yii::$app->getResponse()->setStatusCode(200);
        \Yii::$app->getResponse()->format = 'json';
        \Yii::$app->getResponse()->send();
    }

}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;

class SiteController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    public function actionStatistic()
    {
        return $this->render('statistic');
    }

    public function actionAbout()
    {
        return $this->render('about');
    }
}

views/site/about.php
<?php
use yii\helpers\Html;

/* @var $this yii\web\View */
$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/contact.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

    <div class="alert alert-success">
        Thank you for contacting us. We will respond to you as soon as possible.
    </div>

    <p>
        Note that if you turn on the Yii debugger, you should be able
        to view the mail message on the mail panel of the debugger.
        <?php if (Yii::$app->mailer->useFileTransport): ?>
        Because the application is in development mode, the email is not sent but saved as
        a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
        Please configure the <code>useFileTransport</code> property of the <code>mail</code>
        application component to be false to enable email sending.
        <?php endif; ?>
    </p>

    <?php else: ?>

    <p>
        If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.
    </p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>
                <?= $form->field($model, 'name') ?>
                <?= $form->field($model, 'email') ?>
                <?= $form->field($model, 'subject') ?>
                <?= $form->field($model, 'body')->textArea(['rows' => 6]) ?>
                <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                    'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                ]) ?>
                <div class="form-group">
                    <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php
/* @var $this yii\web\View */
use miloschuman\highcharts\Highcharts;
use yii\helpers\Url;

$this->title = 'Minsk Toilet';
$closedStatusText = '<i class="fa fa-minus-circle fa-5x"></i>';
$openStatusText = '<i class="fa fa-check-circle fa-5x"></i>';
?>
<div class="site-index">

    <div class="jumbotron">
        <h1>Поздравляю!</h1>

        <p class="lead">Теперь тут будут появляться всякие интересные штуки про туалет.</p>

<?php
    $toiletStatus = \Yii::$app->toilet->getStatus();
?>

        <p><a id="btnStatus" style="pointer-events: none;" class="btn btn-lg btn-<?= $toiletStatus?'danger':'success' ?>" href="#"><?= $toiletStatus? $closedStatusText : $openStatusText ?></a></p>
        <script>
            var timeout = 15;
            var currentValue = 15;
            var currentStatus = <?= $toiletStatus?'true':'false' ?>;
            var timer= null;
            var faviconFree = 'favicon-free.ico';
            var faviconClosed = 'favicon-closed.ico';
            var versionService = <?= \Yii::$app->toilet->getVersion(); ?>;

            document.head || (document.head = document.getElementsByTagName('head')[0]);

            function changeFavicon(src) {
                var link = document.createElement('link'),
                    oldLink = document.getElementById('dynamic-favicon');
                link.id = 'dynamic-favicon';
                link.rel = 'shortcut icon';
                link.href = src;
                if (oldLink) {
                    document.head.removeChild(oldLink);
                }
                document.head.appendChild(link);
            }

            function startTimer(){
                timer = setInterval(function(){
                    if(currentValue == 1){
                        updateStatus();
                        currentValue = timeout;
                    }else{
                        currentValue --;
                    }

                    //update progressbar
                    var percent = currentValue*100/timeout;
                    $('#progress').attr('aria-valuemax', timeout).attr('aria-valuenow', currentValue).css('width', percent + '%');
                }, 500);
            }

            startTimer();

            function updateStatus(){
                timeout = null;
                $.ajax({
                    url: '<?= Url::toRoute('api/status'); ?>',
                    dataType: 'json',
                    beforeSend: function(){
                        timeout = setTimeout(function(){
                            $('#btnStatus').html('<i class="fa fa-refresh fa-spin  fa-5x"></i>');
                        }, 100);
                        clearInterval(timer);
                    },
                    success: function(data){
                        //data.status = (Math.floor(Math.random() * 2) + 0) == 1;
                        //data.status
                        if(data.version > versionService){
                            window.location.reload();
                            return false;
                        }
                        var classBtn = 'btn-success';
                        var textBtn = '<?= $openStatusText; ?>';
                        var fav = faviconFree;
                        if(data.status) {
                            classBtn = 'btn-danger';
                            textBtn = '<?= $closedStatusText; ?>';
                            fav = faviconClosed;
                        }
                        clearTimeout(timeout);
                        $('#btnStatus').removeClass('btn-danger').removeClass('btn-success').addClass(classBtn).html(textBtn);

                        $('#visitorsToday').html(data.visits_today);
                        changeFavicon('/'+fav);
                    },
                    complete: function(){
                        startTimer();
                    }
                });
            }
        </script>
        <div class="progress">
            <div id="progress" class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" >
            </div>
        </div>

        <p>За сегодня количество посещений туалета: <strong id="visitorsToday"><?= \Yii::$app->toilet->getVisitsToday(); ?></strong></p>

    </div>

</div>

views/site/login.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'options' => ['class' => 'form-horizontal'],
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

    <?= $form->field($model, 'username') ?>

    <?= $form->field($model, 'password')->passwordInput() ?>

    <?= $form->field($model, 'rememberMe', [
        'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
    ])->checkbox() ?>

    <div class="form-group">
        <div class="col-lg-offset-1 col-lg-11">
            <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>

    <div class="col-lg-offset-1" style="color:#999;">
        You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>
        To modify the username/password, please check out the code <code>app\models\User::$users</code>.
    </div>
</div>

views/site/statistic.php
<?php
use miloschuman\highcharts\Highcharts;
use yii\helpers\Html;

/* @var $this yii\web\View */
$this->title = 'Туалетная статистика';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?php
        $data = \app\models\ToiletHistory::getAvarageVisitsPerWeekDay();
        $days = array_keys($data);
        $week=array(0=>"вс", "пн","вт","ср","чт","пт","сб");
        $dataValues = [];

        foreach($days as &$day){
            $dataValues[] = $data[$day];
            $day = $week[$day];
        }

        echo Highcharts::widget([
            'options' => [
                'title' => ['text' => 'Средняя посещаемость туалета по дням'],
                'chart' => ['type' => 'column'],
                'xAxis' => [
                    'categories' => $days
                ],
                'yAxis' => [
                    'title' => ['text' => 'Количество посещений']
                ],
                'series' => [
                    ['name' => 'Посещения', 'data' => $dataValues]
                ]
            ]
        ]);
        ?>
    </p>
</div>